import { useState, useRef, useEffect } from 'react'
import { Send, ShieldCheck, ShieldAlert, FileDown, Hash, Bot, Phone, KeyRound } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Skeleton } from '@/components/ui/skeleton'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Label } from '@/components/ui/label'
import { useAuthStore } from '@/store/authStore'
import { useFamilies } from '@/hooks/useDashboard'
import {
  useMessages,
  useSendMessage,
  useMarkMessagesRead,
  useVerifyChain,
} from '@/hooks/useMessages'
import { useChatSocket, useTypingIndicator } from '@/hooks/useChatSocket'
import { useSendPhoneCode, useVerifyPhone } from '@/hooks/useSettings'
import { toast } from '@/hooks/use-toast'
import type { Message } from '@/types/api'
import { cn } from '@/lib/utils'
import jsPDF from 'jspdf'
import { getErrorMessage } from '@/lib/getErrorMessage'

// ── PDF export ────────────────────────────────────────────────────────────────

function exportPDF(messages: Message[], chainValid: boolean) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const margin = 18
  let y = margin

  // Header
  doc.setFillColor(240, 253, 250)
  doc.rect(0, 0, W, 28, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(15, 118, 110)
  doc.text('KidSchedule — Court-Ready Message Export', margin, 12)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(100, 116, 139)
  doc.text(`Exported: ${new Date().toISOString()}`, margin, 19)
  doc.text(
    `Chain integrity: ${chainValid ? 'VERIFIED' : 'VIOLATION DETECTED'}`,
    margin,
    24,
  )
  y = 36

  // Divider
  doc.setDrawColor(203, 213, 225)
  doc.line(margin, y, W - margin, y)
  y += 6

  for (const msg of messages) {
    const date = new Date(msg.createdAt).toLocaleString()
    const sender = msg.isSystemMessage
      ? '[SYSTEM]'
      : `${msg.sender?.firstName ?? ''} ${msg.sender?.lastName ?? ''}`.trim()

    // Check if we need a new page
    if (y > 260) {
      doc.addPage()
      y = margin
    }

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(51, 65, 85)
    doc.text(`${sender}  ·  ${date}`, margin, y)
    y += 5

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(30, 41, 59)
    const lines = doc.splitTextToSize(msg.content, W - margin * 2)
    doc.text(lines, margin, y)
    y += lines.length * 4.5 + 2

    doc.setFont('courier', 'normal')
    doc.setFontSize(6.5)
    doc.setTextColor(148, 163, 184)
    doc.text(`SHA-256: ${msg.contentHash}`, margin, y)
    y += 3.5
    doc.text(`prev:    ${msg.previousHash}`, margin, y)
    y += 7

    doc.setDrawColor(226, 232, 240)
    doc.line(margin, y - 2, W - margin, y - 2)
  }

  // Footer on each page
  const totalPages = doc.getNumberOfPages()
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p)
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(7)
    doc.setTextColor(148, 163, 184)
    doc.text(
      'Generated by KidSchedule · Immutable hash-chained record · Not to be altered',
      margin,
      290,
    )
    doc.text(`Page ${p} / ${totalPages}`, W - margin, 290, { align: 'right' })
  }

  doc.save(`kidschedule-messages-${Date.now()}.pdf`)
}

// ── Hash popover ──────────────────────────────────────────────────────────────

function ShieldPopover({
  msg,
  onClose,
}: {
  msg: Message
  onClose: () => void
}) {
  return (
    <div
      className="absolute z-20 bottom-full mb-2 left-0 w-72 bg-white border border-slate-200 rounded-2xl shadow-xl p-4 text-left"
      onClick={(e) => e.stopPropagation()}
    >
      <div className="flex items-center gap-2 mb-3">
        <ShieldCheck className="w-4 h-4 text-teal-500 shrink-0" />
        <span className="text-xs font-semibold text-slate-700">
          Cryptographically Verified
        </span>
      </div>
      <p className="text-[10px] text-slate-400 mb-1">
        Documented on{' '}
        {new Date(msg.createdAt).toLocaleString(undefined, {
          dateStyle: 'long',
          timeStyle: 'medium',
        })}
      </p>
      <div className="mt-2 space-y-1.5">
        <div>
          <p className="text-[9px] font-medium text-slate-400 uppercase tracking-wide mb-0.5">
            SHA-256 Hash
          </p>
          <p className="font-mono text-[9px] text-slate-600 break-all leading-relaxed">
            {msg.contentHash}
          </p>
        </div>
        <div>
          <p className="text-[9px] font-medium text-slate-400 uppercase tracking-wide mb-0.5">
            Previous Hash
          </p>
          <p className="font-mono text-[9px] text-slate-400 break-all leading-relaxed">
            {msg.previousHash}
          </p>
        </div>
      </div>
      <button
        onClick={onClose}
        className="mt-3 text-[10px] text-slate-400 hover:text-slate-600"
      >
        Close
      </button>
    </div>
  )
}

// ── Message bubble ────────────────────────────────────────────────────────────

function MessageBubble({
  msg,
  isMine,
  senderInitials,
}: {
  msg: Message
  isMine: boolean
  senderInitials: string
}) {
  const [showHash, setShowHash] = useState(false)

  if (msg.isSystemMessage) {
    return (
      <div className="flex justify-center my-3">
        <div className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-50 border border-slate-100 rounded-full text-xs text-slate-400">
          <Bot className="w-3 h-3" />
          {msg.content}
        </div>
      </div>
    )
  }

  return (
    <div className={cn('flex gap-2.5 mb-4', isMine ? 'flex-row-reverse' : 'flex-row')}>
      {!isMine && (
        <Avatar className="h-7 w-7 shrink-0 mt-1">
          <AvatarFallback className="text-[10px]">{senderInitials}</AvatarFallback>
        </Avatar>
      )}
      <div className={cn('max-w-[70%] flex flex-col', isMine ? 'items-end' : 'items-start')}>
        <div
          className={cn(
            'px-4 py-2.5 rounded-2xl text-sm leading-relaxed',
            isMine
              ? 'bg-teal-400 text-white rounded-tr-sm'
              : 'bg-white border border-slate-100 text-slate-700 rounded-tl-sm shadow-sm',
          )}
        >
          {msg.content}
        </div>
        <div
          className={cn(
            'flex items-center gap-1.5 mt-1',
            isMine ? 'flex-row-reverse' : 'flex-row',
          )}
        >
          <span className="text-[10px] text-slate-300">
            {new Date(msg.createdAt).toLocaleTimeString([], {
              hour: '2-digit',
              minute: '2-digit',
            })}
          </span>
          <div className="relative">
            <button
              onClick={() => setShowHash((v) => !v)}
              title="View cryptographic proof"
              className="flex items-center gap-0.5 text-[10px] font-mono text-slate-300 hover:text-teal-500 transition-colors"
            >
              <ShieldCheck className="w-3 h-3" />
              {msg.contentHash.slice(0, 6)}…
            </button>
            {showHash && (
              <ShieldPopover msg={msg} onClose={() => setShowHash(false)} />
            )}
          </div>
        </div>
      </div>
    </div>
  )
}

// ── Phone verification gate ───────────────────────────────────────────────────

function PhoneVerificationGate() {
  const [phone, setPhone] = useState('')
  const [code, setCode] = useState('')
  const [codeSent, setCodeSent] = useState(false)

  const sendCode = useSendPhoneCode()
  const verifyPhone = useVerifyPhone()

  async function handleSendCode() {
    if (!phone.trim()) return
    try {
      await sendCode.mutateAsync(phone.trim())
      setCodeSent(true)
      toast({ title: 'Verification code sent', variant: 'success' })
    } catch (err) {
      toast({ title: 'Failed to send code', description: getErrorMessage(err), variant: 'error' })
    }
  }

  async function handleVerify() {
    if (!code.trim()) return
    try {
      await verifyPhone.mutateAsync({ phone: phone.trim(), code: code.trim() })
      toast({ title: 'Phone verified! You can now use messaging.', variant: 'success' })
    } catch (err) {
      toast({ title: 'Invalid or expired code', description: getErrorMessage(err), variant: 'error' })
    }
  }

  return (
    <div className="max-w-3xl h-[calc(100vh-8rem)] flex flex-col items-center justify-center">
      <div className="bg-white border border-slate-100 rounded-2xl shadow-sm p-8 w-full max-w-md text-center">
        <div className="w-14 h-14 rounded-2xl bg-teal-50 flex items-center justify-center mx-auto mb-4">
          <ShieldCheck className="w-7 h-7 text-teal-500" />
        </div>
        <h3 className="text-lg font-bold text-slate-800 mb-1">Phone Verification Required</h3>
        <p className="text-sm text-slate-400 mb-6">
          Messaging is restricted to verified users to ensure legal integrity of the record.
          Verify your phone number to continue.
        </p>

        <div className="space-y-4 text-left">
          <div className="space-y-1.5">
            <Label>Phone Number</Label>
            <div className="flex gap-2">
              <Input
                type="tel"
                placeholder="+1 555 000 0000"
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                disabled={codeSent}
              />
              <Button
                variant="outline"
                onClick={() => void handleSendCode()}
                disabled={!phone.trim() || sendCode.isPending || codeSent}
                className="shrink-0 gap-1.5"
              >
                <Phone className="w-3.5 h-3.5" />
                {codeSent ? 'Sent' : 'Send Code'}
              </Button>
            </div>
          </div>

          {codeSent && (
            <div className="space-y-1.5">
              <Label>Verification Code</Label>
              <div className="flex gap-2">
                <Input
                  type="text"
                  inputMode="numeric"
                  placeholder="6-digit code"
                  maxLength={6}
                  value={code}
                  onChange={(e) => setCode(e.target.value)}
                />
                <Button
                  onClick={() => void handleVerify()}
                  disabled={code.length < 6 || verifyPhone.isPending}
                  className="shrink-0 gap-1.5"
                >
                  <KeyRound className="w-3.5 h-3.5" />
                  Verify
                </Button>
              </div>
              <button
                className="text-xs text-slate-400 hover:text-slate-600"
                onClick={() => { setCodeSent(false); setCode('') }}
              >
                Use a different number
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// ── Page ──────────────────────────────────────────────────────────────────────

export function MessagesPage() {
  const user = useAuthStore((s) => s.user)
  const { data: families } = useFamilies()
  const familyId = families?.[0]?.id

  const { data, isLoading } = useMessages(familyId)
  const messages = data?.messages ?? []

  const sendMessage = useSendMessage(familyId ?? '')
  const markRead = useMarkMessagesRead(familyId ?? '')
  const { data: chain } = useVerifyChain(familyId)

  // Real-time socket: keeps messages cache fresh + typing indicator
  useChatSocket(familyId)
  const { typingUserId, sendTyping, sendStopTyping } = useTypingIndicator(familyId)

  const [text, setText] = useState('')
  const bottomRef = useRef<HTMLDivElement>(null)

  // Auto-scroll and mark read on new messages
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' })
    if (familyId && messages.length > 0) {
      markRead.mutate()
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [messages.length, familyId])

  // Close any open hash popover on outside click
  useEffect(() => {
    const handler = () => {}
    document.addEventListener('click', handler)
    return () => document.removeEventListener('click', handler)
  }, [])

  async function handleSend() {
    if (!text.trim() || !familyId) return
    const content = text.trim()
    setText('')
    sendStopTyping()
    try {
      await sendMessage.mutateAsync(content)
    } catch (err) {
      toast({ title: 'Failed to send message', description: getErrorMessage(err), variant: 'error' })
      setText(content)
    }
  }

  function handleKeyDown(e: React.KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      void handleSend()
    }
  }

  const chainValid = chain?.isValid ?? true

  if (!user?.isVerified) return <PhoneVerificationGate />

  return (
    <div className="max-w-3xl h-[calc(100vh-8rem)] flex flex-col">
      {/* Header */}
      <div className="flex items-center justify-between mb-4 shrink-0">
        <div>
          <h2 className="text-xl font-bold text-slate-800">Family Messages</h2>
          <div className="flex items-center gap-1.5 mt-0.5">
            {chainValid ? (
              <ShieldCheck className="w-3.5 h-3.5 text-teal-500" />
            ) : (
              <ShieldAlert className="w-3.5 h-3.5 text-red-500" />
            )}
            <p
              className={cn(
                'text-xs',
                chainValid ? 'text-teal-600' : 'text-red-500 font-medium',
              )}
            >
              {chain
                ? chainValid
                  ? `Chain verified · ${chain.totalMessages} messages`
                  : `Chain violation detected · ${chain.violations.length} issue(s)`
                : 'Cryptographically hashed for legal integrity'}
            </p>
          </div>
        </div>
        <Button
          variant="outline"
          size="sm"
          className="gap-2"
          onClick={() => {
            if (!messages.length) {
              toast({ title: 'No messages to export', variant: 'error' })
              return
            }
            exportPDF(messages, chainValid)
          }}
        >
          <FileDown className="w-4 h-4" />
          Export PDF
        </Button>
      </div>

      {/* Chat area */}
      <div className="flex-1 bg-white rounded-2xl border border-slate-100 shadow-sm flex flex-col overflow-hidden">
        <ScrollArea className="flex-1 px-4 py-4">
          {isLoading ? (
            <div className="space-y-4">
              {[1, 2, 3].map((i) => (
                <div
                  key={i}
                  className={cn(
                    'flex gap-2.5',
                    i % 2 === 0 ? 'flex-row-reverse' : '',
                  )}
                >
                  <Skeleton className="h-7 w-7 rounded-full shrink-0" />
                  <Skeleton
                    className={cn(
                      'h-16 rounded-2xl',
                      i % 2 === 0 ? 'w-48' : 'w-64',
                    )}
                  />
                </div>
              ))}
            </div>
          ) : !familyId ? (
            <div className="flex flex-col items-center justify-center h-40 text-center">
              <Hash className="w-8 h-8 text-slate-200 mb-3" />
              <p className="text-sm text-slate-400">
                You need a family to send messages.
              </p>
            </div>
          ) : messages.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-40 text-center">
              <Hash className="w-8 h-8 text-slate-200 mb-3" />
              <p className="text-sm text-slate-400">
                No messages yet. Start the conversation.
              </p>
            </div>
          ) : (
            <>
              {messages.map((msg) => {
                const isMine = msg.senderId === user?.id
                const initials = msg.sender
                  ? `${msg.sender.firstName[0]}${msg.sender.lastName[0]}`.toUpperCase()
                  : '??'
                return (
                  <MessageBubble
                    key={msg.id}
                    msg={msg}
                    isMine={isMine}
                    senderInitials={initials}
                  />
                )
              })}
              <div ref={bottomRef} />
            </>
          )}
        </ScrollArea>

        {/* Typing indicator */}
        {typingUserId && typingUserId !== user?.id && (
          <div className="px-4 pb-1 flex items-center gap-1.5">
            <span className="flex gap-0.5">
              {[0, 1, 2].map((i) => (
                <span
                  key={i}
                  className="w-1.5 h-1.5 rounded-full bg-slate-300 animate-bounce"
                  style={{ animationDelay: `${i * 150}ms` }}
                />
              ))}
            </span>
            <span className="text-[11px] text-slate-400">Co-parent is typing…</span>
          </div>
        )}

        {/* Input */}
        <div className="border-t border-slate-100 p-3 shrink-0">
          <div className="flex items-center gap-2">
            <Input
              value={text}
              onChange={(e) => { setText(e.target.value); sendTyping() }}
              onKeyDown={handleKeyDown}
              placeholder="Type a message… (Enter to send)"
              disabled={!familyId || sendMessage.isPending}
              className="flex-1"
            />
            <Button
              size="icon"
              onClick={() => void handleSend()}
              disabled={!text.trim() || !familyId || sendMessage.isPending}
              className="shrink-0"
            >
              <Send className="w-4 h-4" />
            </Button>
          </div>
          <p className="text-[10px] text-slate-300 mt-1.5 text-center">
            Messages are immutable and hash-chained · Click{' '}
            <ShieldCheck className="w-2.5 h-2.5 inline" /> to view proof · Court-ready PDF available
          </p>
        </div>
      </div>
    </div>
  )
}
